language: ruby
env:
  - CI=true
before_script:
  - "bundle exec rake db:prepare"
rvm:
  - 2.5.9
  - 2.6.10
  - 2.7.6
  - 3.0.4
  - 3.1.2
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails61.gemfile
notifications:
  recipients:
    - gabriel.sobrinho@gmail.com
    - thiago.pradi@gmail.com
